spring:
  application:
    name: family-reminder-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/family
    username: family
    password: family
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

security:
  jwt:
    secret: ${SECURITY_JWT_SECRET:ChangeMeChangeMeChangeMeChangeMe}

logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
